// South Platte River Watershed Station Directory
// Curated list of stations from Continental Divide Headwaters to Chatfield Reservoir
// Data sourced dynamically from USGS NWIS and Colorado DWR (CDSS HydroBase)

export const STATIONS = [
  // --- SECTION: HEADWATERS (Middle Fork & South Fork South Park) ---
  {
    id: 'MFKABMCO',
    code: 'MFKABMCO',
    agency: 'CDWR',
    name: 'Middle Fork South Platte abv Montgomery Reservoir',
    shortName: 'MF abv Montgomery Res',
    stream: 'Middle Fork South Platte River',
    location: 'Near Alma, CO (Hoosier Pass)',
    county: 'Park County',
    elevation: '10,870 ft',
    section: 'headwaters',
    branch: 'middle_fork',
    lat: 39.356488,
    lon: -106.082841,
    order: 1,
    milestone: 'Headwaters • 10,870 ft',
    desc: 'Highest monitored station in the watershed, capturing snowmelt above Montgomery Reservoir just below the Continental Divide.',
    typicalRange: '2 - 35 cfs'
  },
  {
    id: 'MFKBLMCO',
    code: 'MFKBLMCO',
    agency: 'CDWR',
    name: 'Middle Fork South Platte blw Montgomery Reservoir',
    shortName: 'MF blw Montgomery Res',
    stream: 'Middle Fork South Platte River',
    location: 'Near Alma, CO',
    county: 'Park County',
    elevation: '10,750 ft',
    section: 'headwaters',
    branch: 'middle_fork',
    lat: 39.352071,
    lon: -106.069368,
    order: 2,
    milestone: 'Montgomery Reservoir Outflow',
    desc: 'Controlled release from Montgomery Reservoir dam flowing down towards Alma and Fairplay.',
    typicalRange: '2 - 40 cfs'
  },
  {
    id: 'MFKPRICO',
    code: 'MFKPRICO',
    agency: 'CDWR',
    name: 'Middle Fork South Platte at Prince',
    shortName: 'MF at Prince (Fairplay/Como)',
    stream: 'Middle Fork South Platte River',
    location: 'Between Fairplay & Hartsel, CO',
    county: 'Park County',
    elevation: '9,120 ft',
    section: 'headwaters',
    branch: 'middle_fork',
    lat: 39.109746,
    lon: -105.890472,
    order: 3,
    milestone: 'South Park High Plains',
    desc: 'Meandering meadow section of the Middle Fork flowing through the high elevation South Park basin.',
    typicalRange: '10 - 75 cfs'
  },
  {
    id: 'MFKSTMCO',
    code: 'MFKSTMCO',
    agency: 'CDWR',
    name: 'Middle Fork South Platte at Santa Maria',
    shortName: 'MF at Santa Maria Ranch',
    stream: 'Middle Fork South Platte River',
    location: 'Near Hartsel, CO',
    county: 'Park County',
    elevation: '8,950 ft',
    section: 'headwaters',
    branch: 'middle_fork',
    lat: 39.058242,
    lon: -105.816156,
    order: 4,
    milestone: 'Pre-Confluence Lower Middle Fork',
    desc: 'Lower Middle Fork near historic Santa Maria Ranch just before joining South Fork above Spinney Mountain Reservoir.',
    typicalRange: '10 - 100 cfs'
  },
  {
    id: 'SFKANTCO',
    code: 'SFKANTCO',
    agency: 'CDWR',
    name: 'South Fork of South Platte abv Antero Reservoir',
    shortName: 'SF abv Antero Res',
    stream: 'South Fork South Platte River',
    location: 'Near Fairplay / Hartsel, CO',
    county: 'Park County',
    elevation: '9,020 ft',
    section: 'headwaters',
    branch: 'south_fork',
    lat: 39.070705,
    lon: -105.97343,
    order: 5,
    milestone: 'South Fork Inflow to Antero',
    desc: 'Originates near Weston Pass in the Mosquito Range, serving as primary inlet stream to Denver Water’s Antero Reservoir.',
    typicalRange: '3 - 40 cfs'
  },
  {
    id: 'PLAANTCO',
    code: 'PLAANTCO',
    agency: 'CDWR',
    name: 'South Platte River blw Antero Reservoir',
    shortName: 'South Platte blw Antero Dam',
    stream: 'South Fork / South Platte River',
    location: 'Near Hartsel, CO',
    county: 'Park County',
    elevation: '8,920 ft',
    section: 'headwaters',
    branch: 'south_fork',
    lat: 38.993886,
    lon: -105.894583,
    order: 6,
    milestone: 'Antero Reservoir Outflow',
    desc: 'Controlled discharge from Antero Reservoir dam, joining the Middle Fork near Hartsel.',
    typicalRange: '2 - 60 cfs'
  },
  {
    id: 'PLASPICO',
    code: 'PLASPICO',
    agency: 'CDWR',
    name: 'South Platte River abv Spinney Reservoir',
    shortName: 'South Platte abv Spinney Res',
    stream: 'South Platte River (Main Stem)',
    location: 'Near Hartsel, CO',
    county: 'Park County',
    elevation: '8,710 ft',
    section: 'headwaters',
    branch: 'main_stem',
    lat: 38.996808,
    lon: -105.680618,
    order: 7,
    milestone: 'Combined Main Stem • Spinney Inflow',
    desc: 'Flow of the unified South Platte River main stem (post Middle & South Fork confluence) into Spinney Mountain Reservoir.',
    typicalRange: '15 - 120 cfs'
  },
  {
    id: 'PLAHARCO',
    code: 'PLAHARCO',
    agency: 'CDWR',
    name: 'South Platte River abv Elevenmile Reservoir',
    shortName: 'Dream Stream (Spinney to Elevenmile)',
    stream: 'South Platte River (Main Stem)',
    location: 'Between Spinney & Elevenmile, CO',
    county: 'Park County',
    elevation: '8,600 ft',
    section: 'headwaters',
    branch: 'main_stem',
    lat: 38.967805,
    lon: -105.581544,
    order: 8,
    milestone: 'Gold Medal "Dream Stream"',
    desc: 'Renowned Gold Medal trout fishery water between Spinney Mountain Reservoir dam and Elevenmile Canyon Reservoir.',
    typicalRange: '40 - 150 cfs'
  },
  {
    id: 'PLAGEOCO',
    code: 'PLAGEOCO',
    agency: 'CDWR',
    name: 'South Platte River near Lake George',
    shortName: 'Elevenmile Canyon at Lake George',
    stream: 'South Platte River (Main Stem)',
    location: 'Lake George, CO',
    county: 'Park County',
    elevation: '7,920 ft',
    section: 'headwaters',
    branch: 'main_stem',
    lat: 38.905278,
    lon: -105.473338,
    order: 9,
    milestone: 'Elevenmile Canyon Tailwater',
    desc: 'Flow emerging from scenic Elevenmile Canyon Gold Medal reach into the town of Lake George.',
    typicalRange: '50 - 250 cfs'
  },

  // --- SECTION: TRIBUTARY - TARRYALL CREEK ---
  {
    id: '06696980',
    code: '06696980',
    agency: 'USGS',
    name: 'Tarryall Creek at Upper Station near Como',
    shortName: 'Tarryall Creek nr Como',
    stream: 'Tarryall Creek (Tributary)',
    location: 'Near Como / Boreas Pass, CO',
    county: 'Park County',
    elevation: '9,600 ft',
    section: 'tributaries',
    branch: 'tarryall',
    lat: 39.33942424,
    lon: -105.91170596,
    order: 10,
    milestone: 'Upper Tarryall Creek Basin',
    desc: 'USGS stream gauge monitoring the pristine headwaters of Tarryall Creek below Como.',
    typicalRange: '4 - 40 cfs'
  },
  {
    id: 'TARTARCO',
    code: 'TARTARCO',
    agency: 'CDWR',
    name: 'Tarryall Creek blw Tarryall Reservoir',
    shortName: 'Tarryall Creek blw Reservoir',
    stream: 'Tarryall Creek (Tributary)',
    location: 'Near Lake George / Park County',
    county: 'Park County',
    elevation: '8,800 ft',
    section: 'tributaries',
    branch: 'tarryall',
    lat: 39.213600,
    lon: -105.578600,
    order: 11,
    milestone: 'Tarryall Reservoir Release',
    desc: 'Tarryall Creek discharge downstream of Tarryall Reservoir before it joins the South Platte River.',
    typicalRange: '5 - 60 cfs'
  },

  // --- SECTION: CHEESMAN & DECKERS ---
  {
    id: '06700000',
    code: '06700000',
    agency: 'USGS',
    name: 'South Platte River abv Cheesman Lake',
    shortName: 'South Platte abv Cheesman Lake',
    stream: 'South Platte River (Main Stem)',
    location: 'Above Cheesman Lake, CO',
    county: 'Douglas / Park County',
    elevation: '6,850 ft',
    section: 'middle',
    branch: 'main_stem',
    lat: 39.162778,
    lon: -105.309722,
    order: 12,
    milestone: 'Cheesman Lake Inflow',
    desc: 'Key USGS gauge tracking the rugged canyon inflow directly into Cheesman Lake reservoir.',
    typicalRange: '60 - 300 cfs'
  },
  {
    id: 'PLACHECO',
    code: 'PLACHECO',
    agency: 'CDWR',
    name: 'South Platte River blw Cheesman Reservoir',
    shortName: 'Cheesman Canyon (blw Dam)',
    stream: 'South Platte River (Main Stem)',
    location: 'Cheesman Canyon, CO',
    county: 'Jefferson / Douglas County',
    elevation: '6,650 ft',
    section: 'middle',
    branch: 'main_stem',
    lat: 39.209275,
    lon: -105.268136,
    order: 13,
    milestone: 'Gold Medal Cheesman Canyon',
    desc: 'Denver Water dam release into world-famous Cheesman Canyon, premier Gold Medal tailwater fishery.',
    typicalRange: '70 - 450 cfs'
  },
  {
    id: '06701900',
    code: '06701900',
    agency: 'USGS',
    name: 'South Platte River blw Brush Creek nr Trumbull',
    shortName: 'South Platte at Deckers / Trumbull',
    stream: 'South Platte River (Main Stem)',
    location: 'Deckers / Trumbull, CO',
    county: 'Douglas County',
    elevation: '6,360 ft',
    section: 'middle',
    branch: 'main_stem',
    lat: 39.25999025,
    lon: -105.2219379,
    order: 14,
    milestone: 'Deckers Recreation Corridor',
    desc: 'Central stream gauge for the popular Deckers stretch, below the Highway 67 bridge.',
    typicalRange: '80 - 500 cfs'
  },

  // --- SECTION: NORTH FORK SOUTH PLATTE & ROBERTS TUNNEL ---
  {
    id: 'ROBTUNCO',
    code: 'ROBTUNCO',
    agency: 'CDWR',
    name: 'Roberts Tunnel at East Portal nr Grant',
    shortName: 'Roberts Tunnel (Dillon Transbasin)',
    stream: 'Harold D. Roberts Tunnel Diversion',
    location: 'Grant, CO (US-285)',
    county: 'Park County',
    elevation: '8,680 ft',
    section: 'north_fork',
    branch: 'north_fork',
    lat: 39.46163,
    lon: -105.676696,
    order: 15,
    milestone: 'Continental Divide Transbasin Inflow',
    desc: '23-mile transbasin tunnel conveying Western Slope water from Lake Dillon under the Continental Divide directly into the North Fork.',
    typicalRange: '0 - 500 cfs'
  },
  {
    id: 'PLAGRACO',
    code: 'PLAGRACO',
    agency: 'CDWR',
    name: 'North Fork South Platte River at Grant',
    shortName: 'North Fork at Grant',
    stream: 'North Fork South Platte River',
    location: 'Grant, CO',
    county: 'Park County',
    elevation: '8,620 ft',
    section: 'north_fork',
    branch: 'north_fork',
    lat: 39.458018,
    lon: -105.659179,
    order: 16,
    milestone: 'North Fork Upper Reach',
    desc: 'Gauging the North Fork just downstream of the Roberts Tunnel outlet along US Highway 285.',
    typicalRange: '20 - 550 cfs'
  },
  {
    id: 'PLABAICO',
    code: 'PLABAICO',
    agency: 'CDWR',
    name: 'North Fork South Platte River at Bailey',
    shortName: 'North Fork at Bailey',
    stream: 'North Fork South Platte River',
    location: 'Bailey, CO',
    county: 'Park County',
    elevation: '7,730 ft',
    section: 'north_fork',
    branch: 'north_fork',
    lat: 39.404767,
    lon: -105.473828,
    order: 17,
    milestone: 'North Fork Canyon Reach',
    desc: 'North Fork river station at Bailey, monitoring flow through Pine Valley and Foxton towards the confluence.',
    typicalRange: '25 - 550 cfs'
  },

  // --- SECTION: LOWER CANYON & WATERTON TO CHATFIELD ---
  {
    id: 'PLASPLCO',
    code: 'PLASPLCO',
    agency: 'CDWR',
    name: 'South Platte River at South Platte',
    shortName: 'Main Stem & North Fork Confluence',
    stream: 'South Platte River (Main Stem)',
    location: 'South Platte, CO (Foxton Rd)',
    county: 'Jefferson County',
    elevation: '6,080 ft',
    section: 'lower',
    branch: 'main_stem',
    lat: 39.40887,
    lon: -105.169876,
    order: 18,
    milestone: 'North Fork & Main Stem Confluence',
    desc: 'Historic confluence where the North Fork joins the Main Stem before entering Strontia Springs Reservoir.',
    typicalRange: '100 - 800 cfs'
  },
  {
    id: 'PLASTRCO',
    code: 'PLASTRCO',
    agency: 'CDWR',
    name: 'South Platte River blw Strontia Springs',
    shortName: 'Waterton Canyon blw Strontia Dam',
    stream: 'South Platte River (Main Stem)',
    location: 'Upper Waterton Canyon, CO',
    county: 'Douglas / Jefferson County',
    elevation: '5,880 ft',
    section: 'lower',
    branch: 'main_stem',
    lat: 39.435068,
    lon: -105.123774,
    order: 19,
    milestone: 'Waterton Canyon Recreation Trail',
    desc: 'Release below Strontia Springs Dam into the 6.2-mile scenic Waterton Canyon gravel trail, home to bighorn sheep.',
    typicalRange: '30 - 300 cfs'
  },
  {
    id: 'PLAWATCO',
    code: 'PLAWATCO',
    agency: 'CDWR',
    name: 'South Platte River at Waterton',
    shortName: 'Waterton Canyon at Chatfield Inflow',
    stream: 'South Platte River (Main Stem)',
    location: 'Waterton Trailhead / Littleton, CO',
    county: 'Douglas / Jefferson County',
    elevation: '5,500 ft',
    section: 'lower',
    branch: 'main_stem',
    lat: 39.488332,
    lon: -105.092773,
    order: 20,
    milestone: 'Primary Chatfield Reservoir Inflow',
    desc: 'Main stem river entry into Chatfield Reservoir at the Waterton Canyon Trailhead.',
    typicalRange: '25 - 400 cfs'
  },

  // --- SECTION: PLUM CREEK (CHATFIELD TRIBUTARY) ---
  {
    id: '06709000',
    code: '06709000',
    agency: 'USGS',
    name: 'Plum Creek near Sedalia',
    shortName: 'Plum Creek nr Sedalia',
    stream: 'Plum Creek (Tributary)',
    location: 'Sedalia, CO',
    county: 'Douglas County',
    elevation: '5,780 ft',
    section: 'tributaries',
    branch: 'plum_creek',
    lat: 39.43831639,
    lon: -104.98306724,
    order: 21,
    milestone: 'Plum Creek Drainage',
    desc: 'USGS station monitoring major southern drainage basin rising from the Palmer Divide.',
    typicalRange: '5 - 50 cfs'
  },
  {
    id: '06709530',
    code: '06709530',
    agency: 'USGS',
    name: 'Plum Creek at Titan Road nr Louviers',
    shortName: 'Plum Creek at Titan Rd (Chatfield Inflow)',
    stream: 'Plum Creek (Tributary)',
    location: 'Titan Rd / Louviers, CO',
    county: 'Douglas County',
    elevation: '5,450 ft',
    section: 'lower',
    branch: 'plum_creek',
    lat: 39.50736944,
    lon: -105.0244667,
    order: 22,
    milestone: 'Plum Creek Chatfield Inflow',
    desc: 'Direct southern tributary inflow of Plum Creek into the south delta of Chatfield Reservoir.',
    typicalRange: '5 - 60 cfs'
  },

  // --- SECTION: CHATFIELD RESERVOIR OUTFLOW ---
  {
    id: 'PLACHACO',
    code: 'PLACHACO',
    agency: 'CDWR',
    name: 'South Platte River blw Chatfield Reservoir',
    shortName: 'South Platte blw Chatfield Dam',
    stream: 'South Platte River (Main Stem)',
    location: 'Littleton, CO (Chatfield Dam)',
    county: 'Jefferson / Arapahoe County',
    elevation: '5,390 ft',
    section: 'lower',
    branch: 'main_stem',
    lat: 39.562682,
    lon: -105.059753,
    order: 23,
    milestone: 'Chatfield Dam Outflow',
    desc: 'Controlled release from US Army Corps Chatfield Dam entering the Denver metropolitan corridor.',
    typicalRange: '10 - 500 cfs'
  }
];

export const SECTIONS = [
  { id: 'all', label: 'All Stations', count: 23 },
  { id: 'headwaters', label: 'Headwaters & South Park', count: 9 },
  { id: 'middle', label: 'Cheesman & Deckers', count: 3 },
  { id: 'north_fork', label: 'North Fork & Roberts Tunnel', count: 3 },
  { id: 'lower', label: 'Waterton & Chatfield', count: 5 },
  { id: 'tributaries', label: 'Tributaries (Tarryall & Plum Cr)', count: 3 }
];
